### ISSUE TITLE
use flag qt5

### ISSUE THREAD

**Issue by Keridos** [saintdev/obs-studio-overlay#1]
Although i unmasked and installed all the qt5 packages, and added qt5 for the program in my package.use it seems to never compile with qt5 support for some reason.

**Comment by saintdev** [comment]
Oh right, I forgot they had use.masked the qt5 USE flag.

You will need to add `media-video/obs-studio -qt5` to /etc/portage/profile/package.use.mask. I'll add this to the README and add a file to symlink into package.use.mask.

**Comment by Keridos** [comment]
Works now, thanks!
