### ISSUE TITLE
adding gentoo repository results in a failure

### ISSUE THREAD

**Issue by helmchenlord** [saintdev/obs-studio-overlay#10]
layman -o https://github.com/saintdev/obs-studio-overlay/blob/master/layman.xml -f -a obs-studio-overlay
- Fetching remote list,...
- Fetching new list... https://github.com/saintdev/obs-studio-overlay/blob/master/layman.xml
- Last-modified: Wed, 13 May 2015 10:57:26 GMT
- Failed to fetch overlay list!
-  Original Error was: Failed to parse the overlays list fetched from https://github.com/saintdev/obs-studio-overlay/blob/master/layman.xml
- This means that the downloaded file is somehow corrupt or there was a problem with the webserver. Check the content of the file. Error was:
- not well-formed (invalid token): line 32, column 70
- Adding overlay,...
- Exception: Overlay "obs-studio-overlay" does not exist.
- CLI: Errors occurred processing action fetch
- Failed to fetch overlay list!
-  Original Error was: Failed to parse the overlays list fetched from https://github.com/saintdev/obs-studio-overlay/blob/master/layman.xml
- This means that the downloaded file is somehow corrupt or there was a problem with the webserver. Check the content of the file. Error was:
- not well-formed (invalid token): line 32, column 70
- CLI: Errors occurred processing action add
- Exception: Overlay "obs-studio-overlay" does not exist.

**Comment by saintdev** [comment]
> layman -o https://github.com/saintdev/obs-studio-overlay/blob/master/layman.xml -f -a obs-studio-overlay

You are attempting to add the github HTML page for that file instead of the layman.xml file. Open https://github.com/saintdev/obs-studio-overlay/blob/master/layman.xml in your broswer and use the Raw link.
