### ISSUE TITLE
media-video/obs-studio-0.13.2 fails to build: cmake-utils_use_disable is banned in EAPI 6 and later: use -DDISABLE_LIBFDK="$(usex fdk)" insteadss

### ISSUE THREAD

**Issue by liuhongxuan23** [saintdev/obs-studio-overlay#21]
Installed portage version: sys-apps/portage-2.2.27

build.log:

[32;01m \* [39;49;00mPackage:    media-video/obs-studio-0.13.2
[32;01m \* [39;49;00mRepository: obs-studio-overlay
[32;01m \* [39;49;00mMaintainer: saintdev@gmail.com
[32;01m \* [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux pulseaudio qt5 truetype userland_GNU
[32;01m \* [39;49;00mFEATURES:   preserve-libs sandbox userpriv usersandbox

> > > Unpacking source...
> > > Unpacking obs-studio-0.13.2.tar.gz to /var/tmp/portage/media-video/obs-studio-0.13.2/work
> > > Source unpacked in /var/tmp/portage/media-video/obs-studio-0.13.2/work
> > > Preparing source in /var/tmp/portage/media-video/obs-studio-0.13.2/work/obs-studio-0.13.2 ...
> > > 已删除'/var/tmp/portage/media-video/obs-studio-0.13.2/work/obs-studio-0.13.2/cmake/Modules/FindFreetype.cmake'
> > > Source prepared.
> > > Configuring source in /var/tmp/portage/media-video/obs-studio-0.13.2/work/obs-studio-0.13.2 ...
> > >  [31;01m_[0m ERROR: media-video/obs-studio-0.13.2::obs-studio-overlay failed (configure phase):
> > >  [31;01m_[0m   cmake-utils_use_disable is banned in EAPI 6 and later: use -DDISABLE_LIBFDK="$(usex fdk)" insteadss
> > >  [31;01m_[0m 
> > >  [31;01m_[0m Call stack:
> > >  [31;01m_[0m     ebuild.sh, line  133:  Called src_configure
> > >  [31;01m_[0m   environment, line 2955:  Called cmake-utils_use_disable 'fdk' 'LIBFDK'
> > >  [31;01m_[0m   environment, line  813:  Called _cmake_use_me_now_inverted 'DISABLE_' 'fdk' 'LIBFDK'
> > >  [31;01m_[0m   environment, line  399:  Called die
> > >  [31;01m_[0m The specific snippet of code:
> > >  [31;01m_[0m           die "${FUNCNAME[1]} is banned in EAPI 6 and later: use -D$1${arg}=\"\$(usex $2)\" insteadss";
> > >  [31;01m_[0m 
> > >  [31;01m_[0m If you need support, post the output of `emerge --info '=media-video/obs-studio-0.13.2::obs-studio-overlay'`,
> > >  [31;01m_[0m the complete build log and the output of `emerge -pqv '=media-video/obs-studio-0.13.2::obs-studio-overlay'`.
> > >  [31;01m_[0m The complete build log is located at '/var/tmp/portage/media-video/obs-studio-0.13.2/temp/build.log'.
> > >  [31;01m_[0m The ebuild environment file is located at '/var/tmp/portage/media-video/obs-studio-0.13.2/temp/environment'.
> > >  [31;01m_[0m Working directory: '/var/tmp/portage/media-video/obs-studio-0.13.2/work/obs-studio-0.13.2'
> > >  [31;01m*[0m S: '/var/tmp/portage/media-video/obs-studio-0.13.2/work/obs-studio-0.13.2'

**Comment by saintdev** [comment]
Ugh, I wish they would document this somewhere. Looks like it hadn't made its way downstream when I switched to EAPI=6. Sorry about that.
