### ISSUE TITLE
ConfigHandler.read(); Failed

### ISSUE THREAD

**Issue by sshnip** [saintdev/obs-studio-overlay#4]
Hi. I'm trying to fetch this overlay with layman. I've tried to add this overlay and got exact the same error which I see now when I try to delete this overlay:

---

layman -d obs-studio-overlay
- Deleting selected overlay(s)...
- Deleting directory "/var/lib/layman/obs-studio-overlay"
- ReposConf: ConfigHandler.read(); Failed to read "/etc/portage/repos.conf/layman.conf".
- File not found.
- CLI: Errors occurred processing action delete
- ReposConf: ConfigHandler.read(); Failed to read "/etc/portage/repos.conf/layman.conf".
- File not found.
- Exception caught removing repository 'obs-studio-overlay':
- ConfigHandler instance has no attribute 'repo_conf'
  ___

**Comment by saintdev** [comment]
Sorry, I can't help you. I personally don't use layman. Maybe @flyser can help, he added the layman support files?

If I were to guess from the errors, it looks like layman isn't setup correctly on your end.

**Comment by sshnip** [comment]
Hi. I think this's likely configuration file problem because I use about 5-10 overlays regularly and they works fine.
Offtopic, do you use obs-studio on gentoo? Mb you can tell me another decent way to install this package?

Thanks

**Comment by flyser** [comment]
Hm ... that's odd. It works for me on a fresh gentoo installation.

**Comment by sshnip** [comment]
Hm, let me investigate a bit more, maybe I have broken something.

**Comment by Keridos** [comment]
That is a layman bug. Create /etc/portage/repos.conf/ and run layman-updater -R

**Comment by saintdev** [comment]
@Keridos thanks!

I'm going to go ahead and close this.
