### ISSUE TITLE
repo_name

### ISSUE THREAD

**Issue by Keridos** [saintdev/obs-studio-overlay#5]
The repo_name should be the same as the overlay name, else we get warnings on emerge.

**Comment by saintdev** [comment]
What version of portage are you using? Is this a layman warning? I've never seen any such warning and have several overlays where the directory name is different from the overlay name.

**Comment by Keridos** [comment]
Happened to me on one of my PCs recently, I think yesterday with the current portage version on ~amd64.

**Comment by sshnip** [comment]
Same issue here. Wasn't able to install obs-studio untill renaming in /etc/portage/repos.conf/layman.conf.

**Comment by Keridos** [comment]
Can you maybe merge one of the pull requests? My portage continues to complain about it currently.

**Comment by saintdev** [comment]
Ok, I found where this is coming from.

It looks like this comes from the plug-in sync system. So it seems layman is creating the repo.conf entry with the wrong name.
