### ISSUE TITLE
No jack support?

### ISSUE THREAD

**Issue by sshnip** [saintdev/obs-studio-overlay#7]
Not sure about that but it seems like gentoo version has no jack support?
Developers told they added it like few months ago but I have no jack inputs/outputs with 9999 version installed 2-3 days ago.
Could you please clarify this moment?
Thanks

**Comment by saintdev** [comment]
That is probably my fault. I thought CMake would have picked up the JACK libraries on it's own, but I guess not. I'll look into updating the ebuild.

**Comment by sshnip** [comment]
It would be awesome. Whole my system works via jack or pulseaudio_to_jack, also I wanted to add some enhancements (like EQ, compressor and others) for microphone, and most conforming software for linux to do that working with jack (such as ardour).
Thank you very much!

**Comment by saintdev** [comment]
Could you try the [jack](https://github.com/saintdev/obs-studio-overlay/tree/jack) branch and let me know if it works with USE="jack". I don't have JACK installed here to test against.

**Comment by sshnip** [comment]
I'd like to but I don't really know how can I switch branch using layman?

**Comment by saintdev** [comment]
I don't know. According to the portage sync plugin you can manage branches directly there with git without issues. So try in your obs overlay directory (in /var/lib/layman(?) I think):

```
git fetch --all
git checkout -b jack origin/jack
```

Assuming layman uses 'origin' for the default remote. To switch back just `git checkout master`.

**Comment by EoD** [comment]
Hmmm, you jack branch is a bit messed up with the merge of master. I think it's better to rebase the jack branch next time :)

Why didn't you merge it to the master branch yet?

**Comment by saintdev** [comment]
> Why didn't you merge it to the master branch yet?

Nobody was able to tell me if it actually enabled JACK or not. I just needed someone to confirm JACK was working in that branch.

> Hmmm, you jack branch is a bit messed up with the merge of master. I think it's better to rebase the jack branch next time :)

I need to enable thin manifests for the repo.

**Comment by Tele42** [comment]
@saintdev I used your ebuild with 0.13.2 and jack sources in obs studio does capture audio. Don't forget to switch the dependency to virtual/jack. Also, feel free to ping me with other jack-related testing you want done.

**Comment by saintdev** [comment]
Thanks for testing and reporting back!
